name: statistical-filters-hoi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.9
  - ipykernel
  - ipywidgets
  - numpy=2.3.4
  - scipy=1.16.3
  - pandas=2.3.3
  - matplotlib=3.10.7
  - seaborn=0.13.2
  - tqdm=4.67.1
  - pip
  - pip:
    - hypergraphx==1.7.8
    - pyarrow==16.0.0
    - powerlaw==2.0.0
